trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'build.proj'
  buildPlatform: 'x64'
  buildConfiguration: 'Debug'

steps:
- checkout: self
  submodules: true
  fetchDepth: 1

- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
